### PR TITLE
Feature/build

### PR DESCRIPTION
**Pull request by rtfmoz2**
Add build versioning for alpaca, this is a precursor for software packaging deployment

### CODE REVIEW

**Review by samuong — COMMENTED** [review]
Thanks for contributing this. But I'm a little confused by the purpose of the build scripts here, before we get into the version stuff, can you help me understand this? Comments below.

**Comment by rtfmoz2** [comment]
Oh crap, its showing the stuff I am currently working on, that was not my intention. Those build scripts are unfinished, let me save my latest commits.

**Comment by rtfmoz2** [comment]
Ok there you go... they will make a lot more sense now.  I haven't decided if there is anything to do post-install yet but some man pages would be nice so I have to figure out how to automagically generate some. Hmm looks for docs on alpaca...

**Comment by samuong** [comment]
What you're saying makes sense, and versioning is something I've been thinking about for a while (see #11) but haven't gotten around to yet. There is no version string anywhere in the code, and I'd like to avoid that if possible. The reason is that they get can in the way of merges, or just forgotten about.

I'm currently thinking that the best way to do this is to pass the output of `git describe --tags` to go via ldflags from GitHub Actions and/or look at the `vcs.revision` (and `vcs.modified`) setting in the [BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo).

I'm not sure exactly what autodocs you'd need; let's continue the conversation over email? I use Gmail and my username there is the same as my GitHub username.

**Comment by rtfmoz2** [comment]
> What you're saying makes sense, and versioning is something I've been thinking about for a while (see #11) but haven't gotten around to yet. There is no version string anywhere in the code, and I'd like to avoid that if possible. The reason is that they can get in the way of merges, or just forgotten about.
> 
> I'm currently thinking that the best way to do this is to pass the output of `git describe --tags` to go via ldflags from GitHub Actions and/or look at the `vcs.revision` (and `vcs.modified`) setting in the [BuildInfo](https://pkg.go.dev/runtime/debug#BuildInfo).
> 
> I'm not sure exactly what autodocs you'd need; let's continue the conversation over email? I use Gmail and my username there is the same as my GitHub username.

I found I can get the version using `git describe --tags | head -1`

**Pull request closed without merging**
